# Basic setting
c_val: 1.0
# threshold_type: [time, generation_num]
threshold_type: time
hours: 72
#generation_num: 100
output_dir: result/IPEA_PI_150w_200
model_setting:
  model_json: model/PI_150w_200/model.json
  model_weight: model/PI_150w_200/model.h5
token: model/PI_150w_200/token.pkl
reward_setting: 
  reward_module: reward.IPEA_reward
  reward_class: IPEA_reward

# Advanced setting
expansion_threshold: 0.995
simulation_num: 1
flush_threshold: -1
policy_setting: 
  policy_module: policy.ucb1
  policy_class: Ucb1

# Restart setting
save_checkpoint: True
restart: False
checkpoint_file: chemtsv2_IPEA_PI_150w_200.ckpt.pkl

# Filter setting
use_lipinski_filter: False
lipinski_filter:
  module: filter.lipinski_filter
  class: LipinskiFilter
  type: rule_of_5
use_radical_filter: True
radical_filter:
  module: filter.radical_filter
  class: RadicalFilter
use_pubchem_filter: False
pubchem_filter:
  module: filter.pubchem_filter
  class: PubchemFilter
use_sascore_filter: False
sascore_filter:
  module: filter.sascore_filter
  class: SascoreFilter
  threshold: 3.5
use_ring_size_filter: False
ring_size_filter:
  module: filter.ring_size_filter
  class: RingSizeFilter
  threshold: 6
use_pains_filter: False
pains_filter:
  module: filter.pains_filter
  class: PainsFilter
  type: [pains_a]
include_filter_result_in_reward: False
